# Generated by Django 4.2.28 on 2026-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('razorpay', 'Razorpay / UPI'), ('cod', 'Cash on Delivery'), ('upi', 'UPI (Direct)')], max_length=20),
        ),
    ]
