# Generated by Django 4.2.28 on 2026-02-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_production_ready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-initiated_at']},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='gateway_txn_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_7ad4af_idx',
            old_name='status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_paid_at_b40014_idx',
            old_name='paid_at_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentlog',
            new_name='payments_pa_payment_e94ce5_idx',
            old_name='payment_log_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('razorpay', 'Razorpay / UPI'), ('esewa', 'eSewa'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='initiated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'),
        ),
    ]
