"""
Razorpay Payment Gateway Integration
- Secure signature verification
- Order creation and tracking
- Webhook handling
"""
import hmac
import hashlib
import json
import logging
import requests
from decimal import Decimal

from django.conf import settings
from django.db import transaction

from .models import Payment, PaymentLog

logger = logging.getLogger(__name__)


class RazorpayIntegrationError(Exception):
    """Custom exception for Razorpay integration errors"""
    pass


class RazorpayClient:
    """Razorpay payment gateway client"""
    
    API_URL = "https://api.razorpay.com/v1"
    
    def __init__(self):
        self.key_id = settings.RAZORPAY_KEY_ID
        self.key_secret = settings.RAZORPAY_KEY_SECRET
        
        if not self.key_id or not self.key_secret:
            raise RazorpayIntegrationError(
                "RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET must be configured"
            )
    
    def _make_request(self, method, endpoint, data=None):
        """Make authenticated request to Razorpay API"""
        url = f"{self.API_URL}{endpoint}"
        auth = (self.key_id, self.key_secret)
        headers = {'Content-Type': 'application/json'}
        
        try:
            if method == 'POST':
                response = requests.post(url, json=data, auth=auth, headers=headers)
            elif method == 'GET':
                response = requests.get(url, auth=auth, headers=headers)
            else:
                raise RazorpayIntegrationError(f"Unsupported HTTP method: {method}")
            
            response.raise_for_status()
            return response.json()
        
        except requests.RequestException as e:
            logger.error(f"Razorpay API error: {str(e)}")
            raise RazorpayIntegrationError(f"API request failed: {str(e)}")
    
    def create_order(self, order_id, amount, currency='INR', receipt=None, notes=None):
        """
        Create a Razorpay order.
        
        Args:
            order_id: Django Order ID (decimal number in paise)
            amount: Amount in paise (multiply by 100)
            currency: Payment currency (INR, USD, etc.)
            receipt: Receipt identifier
            notes: Additional notes/metadata
        
        Returns:
            dict: Razorpay order data
        """
        # Convert to paise if needed
        amount_paise = int(Decimal(amount) * 100)
        
        payload = {
            'amount': amount_paise,
            'currency': currency,
            'receipt': receipt or f'order_{order_id}',
            'notes': notes or {'order_id': order_id}
        }
        
        try:
            response = self._make_request('POST', '/orders', payload)
            logger.info(f"Razorpay order created: {response.get('id')}")
            return response
        except RazorpayIntegrationError as e:
            logger.error(f"Failed to create Razorpay order: {str(e)}")
            raise
    
    def fetch_order(self, razorpay_order_id):
        """Fetch order details from Razorpay"""
        try:
            return self._make_request('GET', f'/orders/{razorpay_order_id}')
        except RazorpayIntegrationError as e:
            logger.error(f"Failed to fetch order {razorpay_order_id}: {str(e)}")
            raise
    
    def fetch_payment(self, razorpay_payment_id):
        """Fetch payment details from Razorpay"""
        try:
            return self._make_request('GET', f'/payments/{razorpay_payment_id}')
        except RazorpayIntegrationError as e:
            logger.error(f"Failed to fetch payment {razorpay_payment_id}: {str(e)}")
            raise
    
    @staticmethod
    def verify_signature(razorpay_order_id, razorpay_payment_id, razorpay_signature):
        """
        Verify Razorpay payment signature.
        
        This verifies the signature generated by Razorpay for security.
        The signature is created by Razorpay as:
        SHA256(order_id|payment_id, key_secret)
        
        Args:
            razorpay_order_id: Order ID from Razorpay
            razorpay_payment_id: Payment ID from Razorpay
            razorpay_signature: Signature to verify
        
        Returns:
            bool: True if signature is valid
        
        Raises:
            RazorpayIntegrationError: If signature is invalid
        """
        message = f"{razorpay_order_id}|{razorpay_payment_id}"
        expected_signature = hmac.new(
            settings.RAZORPAY_KEY_SECRET.encode('utf-8'),
            message.encode('utf-8'),
            hashlib.sha256
        ).hexdigest()
        
        is_valid = hmac.compare_digest(
            expected_signature,
            razorpay_signature
        )
        
        if not is_valid:
            logger.warning(
                f"Invalid signature for order_id={razorpay_order_id}, "
                f"payment_id={razorpay_payment_id}"
            )
            raise RazorpayIntegrationError("Payment signature verification failed")
        
        return True


def process_razorpay_payment(payment, razorpay_payment_id, razorpay_signature):
    """
    Process successful Razorpay payment.
    
    Args:
        payment: Payment model instance
        razorpay_payment_id: Payment ID from Razorpay
        razorpay_signature: Signature from Razorpay
    
    Returns:
        dict: Payment status and order details
    """
    try:
        client = RazorpayClient()
        
        # Verify signature
        RazorpayClient.verify_signature(
            payment.transaction_id,
            razorpay_payment_id,
            razorpay_signature
        )
        
        # Fetch full payment details
        payment_details = client.fetch_payment(razorpay_payment_id)
        
        with transaction.atomic(durable=True):
            # Update payment record
            payment.transaction_id = razorpay_payment_id
            payment.payment_signature = razorpay_signature
            payment.raw_response = payment_details
            payment.mark_as_verified()
            payment.mark_as_paid()
            
            # Update order
            payment.order.status = 'confirmed'
            payment.order.save(update_fields=['status'])
            
            # Log payment
            PaymentLog.objects.create(
                payment=payment,
                status='success',
                message=f'Payment {razorpay_payment_id} verified and captured',
                metadata={
                    'razorpay_payment_id': razorpay_payment_id,
                    'amount': str(payment.amount),
                }
            )
            
            logger.info(
                f"Payment {razorpay_payment_id} processed for "
                f"order {payment.order.order_number}"
            )
        
        return {
            'success': True,
            'payment_id': razorpay_payment_id,
            'order_number': payment.order.order_number,
            'amount': str(payment.amount),
        }
    
    except RazorpayIntegrationError as e:
        logger.error(f"Razorpay integration error: {str(e)}")
        
        with transaction.atomic():
            payment.mark_as_failed(str(e))
            payment.order.status = 'failed'
            payment.order.save(update_fields=['status'])
            
            PaymentLog.objects.create(
                payment=payment,
                status='failed',
                message=f'Payment verification failed: {str(e)}'
            )
        
        raise
    
    except Exception as e:
        logger.error(f"Unexpected error processing Razorpay payment: {str(e)}", exc_info=True)
        
        with transaction.atomic():
            payment.mark_as_failed("Unexpected error during payment processing")
            payment.order.status = 'failed'
            payment.order.save(update_fields=['status'])
        
        raise RazorpayIntegrationError(f"Payment processing failed: {str(e)}")


def validate_razorpay_webhook(request_body, razorpay_signature):
    """
    Validate Razorpay webhook signature.
    
    This ensures the webhook request is actually from Razorpay.
    
    Args:
        request_body: Raw request body (bytes)
        razorpay_signature: Signature header from webhook
    
    Returns:
        bool: True if signature is valid
    """
    expected_signature = hmac.new(
        settings.RAZORPAY_KEY_SECRET.encode('utf-8'),
        request_body,
        hashlib.sha256
    ).hexdigest()
    
    is_valid = hmac.compare_digest(expected_signature, razorpay_signature)
    
    if not is_valid:
        logger.warning(
            f"Invalid webhook signature from Razorpay. "
            f"Expected: {expected_signature}, Got: {razorpay_signature}"
        )
    
    return is_valid
