# Generated by Django 4.2.28 on 2026-02-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_production_ready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='cart_cart_user_id_b645f9_idx',
            old_name='cart_user_idx',
        ),
    ]
